# Generated by Django 5.0.4 on 2024-04-13 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=150)),
                ('user_email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(default='', max_length=80)),
                ('task_desc', models.TextField(default='', max_length=255)),
                ('task_state', models.CharField(choices=[('A', 'A fazer'), ('P', 'Pronto')], default='A', max_length=1)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api_rest.user')),
            ],
        ),
    ]
